name: moglow-pre2
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pytorch
  - cudatoolkit=10.2
  - scikit-learn
  - tensorboardx
  - tqdm
  - docopt
  - pandas
  - joblib
  - librosa

